/* Code generated by ./test/gen_source.rb */

#include "component.h"
#include "downstream.h"
#include <stdbool.h>

void btx_initialize_usr_data(void *btx_handle, void **usr_data) {
}

btx_source_status_t btx_push_usr_messages(void *btx_handle, void *usr_data) {
    btx_push_message_event_2(btx_handle, 0);
    return BTX_SOURCE_END;
}

